ChannelMapping:
- 0:Green
- 1:Red
- 2:Blue
- 3:White
ChannelsToProcess:
- Red
- Green
RoiPrimaryDrawChan: Blue
OutputLocation: None
RecentOpens: []
RecentAnalysisOpen: []
BinningEnabled: false
BinningDrawLabels: true
BinningNumber: 5
BinningExcludeOutliers: true
BinningIncludeNearest: true
MinimumThreshold: 0
UnsharpMaskRadius: 20
UnsharpMaskWeight: 0.8
GaussianSigma: 0.5
Calibrations:
- 'Default (one pixel : 1.0 microns)'
SelectedCalibration: 1
OutputOptionsEnabled:
- ROIDraw(B)
- ROIDrawF(G,R)
- BinDraw(B)
- ProcessedF(G,R)
- DotsNoNum(G,R)
OutputOptionsDisabled:
- Chan()
- ChanTiff()
- MaxedChan()
- ROIDrawD()
- RoiDrawBlank()
- ROIDrawOb()
- ROIDrawDOr()
- ROIDrawDOb()
- ROIDrawObOr()
- ROIDrawDNoNum()
- BinDrawBlank()
- BinDrawF()
- BinDrawD()
- BinDrawOb()
- BinDrawDOb()
- BinDrawDOr()
- BinDrawObOr()
- BinDrawDNoNum()
- ProcessedD()
- ProcessedOb()
- ProcessedDOb()
- ProcessedDOr()
- ProcessedObOr()
