ChannelMapping:
- 0:Green
- 1:Red
- 2:Blue
- 3:White
ChannelsToProcess:
- Red
- Green
ChannelForROIDraw: Blue
OutputLocation: None
RecentOpens: []
RecentAnalysisOpen: []
BinningEnabled: false
BinningDrawLabels: true
BinningNumber: 5
BinningExcludeOutliers: true
BinningChannelsToDraw:
- Blue
MinimumThreshold: 0
UnsharpMaskRadius: 20
UnsharpMaskWeight: 0.8
GaussianSigma: 0.5
Calibrations:
- 'Default (one pixel : 1.0 microns)'
SelectedCalibration: 1