ChannelMapping:
- 0:Green
- 1:Red
- 2:Blue
- 3:White
ChannelsToProcess:
- Red
- Green
ChannelForROIDraw: Blue
OutputLocation: None
RecentOpens: []
RecentAnalysisOpen: []
BinningEnabled: false
BinningDrawLabels: true
BinningNumber: 5
BinningExcludeOutliers: true
BinningChannelsToDraw:
- Blue